#
a=[10,20,'sourabh','tyagi',80]
a.append(45) # adding data in the end
print(a)
a.insert(1,'moolya')
print(a)
a.insert(8,'moolya')
print(a)
a.remove(20)
print(a)
a.remove('sourabh')
print(a)
y=['sourabh','sourabh','alibaba','sourabh',70,80]
y.remove('sourabh')
print(y)
y.remove('sourabh')
print(y)
z=['sourabh','alibaba','moolya','india']
z.sort()
print(z)
j=[1,6,87,65,34,2,45]
j.sort()
print(j)
#k=['india',67,'sourabh',88,'delhi']
#k.sort()
#print(k)
j.reverse()
print(j)
j.clear()
print(j)
h=['sourabh','sourabh','alibaba','sourabh']
print(h.count('sourabh'))

